- name: Копировать ###
  template:
    src: docker-compose.yml.j2 #
    dest: /tmp/docker-compose.yml
    mode: 0700

- name: Запустить docker-compose
  docker_compose:
    project_src: /tmp
    state: present