- name: Создать папку
  file:
    path: /tmp/grafana
    state: directory

- name: Копировать ###
  copy:
    src: Dockerfile
    dest: /tmp/grafana
    mode: 0700

- name: Копировать папку
  synchronize:
    src: files/
    dest: /tmp/grafana


- name: Остановить Docker-контейнер (если существует)
  shell:
    cmd: docker stop grafana && docker rm grafana
  ignore_errors: yes

- name: Удалить старый Docker-образ (если существует)
  shell:
    cmd: docker rmi grafana_image
  ignore_errors: yes

- name: Собрать Docker-образ
  shell:
    cmd: docker build -t grafana_image /tmp


- name: Run Docker container
  docker_container:
    name: grafana
    image: grafana_image
    state: started
    network_mode: host

