- name: =========================== Создаем папку /tmp/ ===========================
  file:
    path: /tmp/grafana
    state: directory

- name: =========================== Копируем Dockerfile ===========================
  copy:
    src: Dockerfile
    dest: /tmp/grafana
    mode: 0700

- name: =========================== Копируем папку ===========================
  synchronize:
    src: files/
    dest: /tmp/grafana


- name: =========================== Остановить Docker-контейнер (если существует) ===========================
  shell:
    cmd: docker stop grafana && docker rm grafana
  ignore_errors: yes
  register: docker_container_result

- name: =========================== Удалить старый Docker-образ (если существует) ===========================
  shell:
    cmd: docker rmi grafana_image
  ignore_errors: yes
  register: docker_image_result

- name: =========================== Удалять нечего ===========================
  debug:
    msg: "Не пугайтесь ошибок выше.
      Если вы видите это сообщение, то скорее всего docker не удалил образ и/или контейнер, 
      что не является в данном playbook ошибкой. Только если в самой ошибке не указано иначе."

  when:
      - docker_container_result.failed
      - docker_image_result.failed