apiVersion: 1
groups:
  - orgId: 1
    name: Watcher
    folder: Llama_alert
    interval: 1m
    rules:
      - uid: a636666c-fe3f-48b4-a414-6d44d86e5978
        title: Llama_current_state
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PFC5A1047F5919892
            model:
              intervalMs: 5000
              maxDataPoints: 43200
              query: SELECT last("rtt") FROM "autogen"."raw_stats" WHERE ("src_hostname"::tag = 'Master-node') AND $timeFilter GROUP BY time(10s), "dst_hostname"::tag
              rawQuery: true
              refId: A
              resultFormat: time_series
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              settings:
                mode: dropNN
              type: reduce
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: $B < 0.0001
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: math
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: Глянь, что с нодой
          summary: Одна из нод упала
        labels: {}
        isPaused: false
contactPoints:
  - orgId: 1
    name: Telegram
    receivers:
      - uid: fdab5401-ef7a-4571-841c-24132005ac6d
        type: telegram
        settings:
          bottoken: 6632274047:AAGeVgjJeDHLAuUwKqbTkLYQMEz3Sv7dluo
          chatid: "-1001985263510"
          disable_notification: false
          disable_web_page_preview: false
          protect_content: false
        disableResolveMessage: false
policies:
  - orgId: 1
    receiver: Telegram
    group_wait: 10s
    group_interval: 1m
    repeat_interval: 5m
