---
- name: ======================= Установка docker-collector на Master =======================
  hosts: module_master_fip_tf
  become: yes
  gather_facts: no
  ignore_errors: true

  roles:
    - collector