---
- name: ===========================  Installing docker-llama on Master ===========================
  hosts: module_master_fip_tf
  become: yes
  gather_facts: no
  ignore_errors: true

- import_playbook: docker_reflector.yml
- import_playbook: docker_collector.yml
- import_playbook: docker_scraper.yml