- name: =========================== Download scraper ===========================
  copy:
    src: scraper
    dest: /usr/local/bin/scraper
    mode: 0755

- name: =========================== Create file scraper.service ===========================
  file:
    path: /etc/systemd/system/scraper.service
    state: touch

- name: =========================== Setup collector.service ===========================
  shell:
    cmd: |
      echo "[Unit]
      Description= Launch scraper

      [Service]
      User=root

      ExecStart=/usr/local/bin/scraper  -llama.collector-hosts {{ llama_collector_hosts }} -llama.collector-port {{ llama_collector_port }} -llama.influxdb-host {{ llama_influxdb_host }} -llama.influxdb-name {{ llama_influxdb_name }} --llama.influxdb-pass {{ llama_influxdb_pass }} -llama.influxdb-port {{ llama_influxdb_port }} -llama.influxdb-user {{ llama_influxdb_user }} -llama.interval {{ llama_interval }}
      Restart=always

      [Install]
      WantedBy=multi-user.target
      " > /etc/systemd/system/scraper.service

- name: =========================== Restart scraper.service ===========================
  service:
    name: scraper.service
    state: restarted
    daemon-reload: true
    enabled: true
