---
- name: ===========================  Installing docker-influx on Master ===========================
  hosts: module_master_fip_tf
  become: yes
  gather_facts: no
  ignore_errors: true

  roles:
    - influxdb