- name: Копировать Dockerfile
  template:
    src: Dockerfile.yaml.j2 #
    dest: /tmp/Dockerfile
    mode: 0700

- name: Копировать reflector
  copy:
    src: reflector #
    dest: /tmp/reflector
    mode: 0700

- name: Остановить Docker-контейнер (если существует)
  shell:
    cmd: docker stop reflector && docker rm reflector
  ignore_errors: yes

- name: Удалить старый Docker-образ (если существует)
  shell:
    cmd: docker rmi reflector_image
  ignore_errors: yes

- name: Собрать Docker-образ
  shell:
    cmd: docker build -t reflector_image /tmp
  args:
    chdir: /tmp

- name: Run Docker container
  docker_container:
    name: reflector
    image: reflector_image
    state: started
    ports:
      - "{{ llama_port_reflector }}:{{ llama_port_reflector }}"

# apt install python-pip
# pip install docker
# sudo apt-get install python3 python3-pip
# sudo pip3 install docker
