- name: =========================== Copy file with owner and permissions ===========================
  copy:
    src: datasource.yaml
    dest: /etc/grafana/provisioning/datasources
    owner: root
    group: root
    mode: "0644"

- name: =========================== Copy dashboards ===========================
  copy:
    src: dashboards
    dest: /etc/grafana
    owner: root
    group: root
    mode: "0644"

- name: =========================== Copy dashboard-provider file with owner and permissions ===========================
  copy:
    src: dashboard-provider.yaml
    dest: /etc/grafana/provisioning/dashboards
    owner: root
    group: root
    mode: "0644"
