---
- name: =========================== Installing docker-llama ===========================
  hosts: type_openstack_compute_instance_v2
  become: yes
  gather_facts: no
  ignore_errors: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Обновить список пакетов
      apt:
        update_cache: yes

    - name: Установить пакеты, необходимые для использования Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3-pip
        state: present

    - name: Добавить официальный ключ Docker GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавить официальный репозиторий Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Установить Docker
      apt:
        name: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
        - docker-compose
        state: present

    - name: Install Docker Module for Python
      pip:
        name: docker


- import_playbook: docker-llama/docker_llama.yml
- import_playbook: docker-influxdb/docker_influxdb.yml
- import_playbook: docker-grafana/docker_grafana.yml
- import_playbook: docker-compose/docker_MEGALLAMA.yml