---
- name: =========================== Installing docker-llama on Nodes ===========================
  hosts: module_nodes_server_tf
  become: yes
  gather_facts: no
  ignore_errors: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - docker-llama