---
- name: ======================= Проверка связности и ОС ========================
  hosts: all
  connection: ssh
  gather_facts: yes
  tasks:
    - name: =========================== Пингуем хосты ===========================
      ping:
      when: ansible_os_family == "Debian"
    - name: Print message
      debug:
        msg: Да, это Ubuntu сервер