- name: =========================== Создаем папку в /tmp/ ===========================
  file:
    path: /tmp/collector
    state: directory
    mode: 0700

- name: =========================== Копируем Dockerfile ===========================
  template:
    src: Dockerfile.yaml.j2 #
    dest: /tmp/collector/Dockerfile
    mode: 0700

- name: =========================== Копируем collector ===========================
  copy:
    src: collector #
    dest: /tmp/collector/collector
    mode: 0700

- name: =========================== Копируем config для collector ===========================
  copy:
    src: complex_example.yaml #
    dest: /tmp/collector/complex_example.yaml
    mode: 0700

- name: =========================== Остановить Docker-контейнер (если существует) ===========================
  shell:
    cmd: docker stop collector && docker rm collector
  ignore_errors: yes
  register: docker_container_result

- name: =========================== Удалить старый Docker-образ (если существует) ===========================
  shell:
    cmd: docker rmi collector_image
  ignore_errors: yes
  register: docker_image_result

- name: =========================== Удалять нечего ===========================
  debug:
    msg: "Не пугайтесь ошибок выше.
      Если вы видите это сообщение, то скорее всего docker не удалил образ и/или контейнер, 
      что не является в данном playbook ошибкой. Только если в самой ошибке не указано иначе."

  when:
      - docker_container_result.failed
      - docker_image_result.failed