    - name: Обновить список пакетов
      apt:
        update_cache: yes

    - name: Установить пакеты, необходимые для использования Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3-pip
        state: present

    - name: Добавить официальный ключ Docker GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавить официальный репозиторий Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Установить Docker
      apt:
        name: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
        state: present

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Копировать Dockerfile
      copy:
        src: Dockerfile.yaml #
        dest: /tmp/Dockerfile

    - name: Копировать reflector
      copy:
        src: reflector #
        dest: /tmp/reflector

    - name: Собрать Docker-образ
      command: docker build -t reflector_image /tmp
      args:
        chdir: /tmp

    - name: Run Docker container
      docker_container:
        name: reflector
        image: reflector_image
        state: started
        ports:
          - "14000:14000"


# apt install python-pip
# pip install docker
# sudo apt-get install python3 python3-pip
# sudo pip3 install docker
