- name: Создать папку
  file:
    path: /tmp/scraper
    state: directory
    
- name: Копировать Dockerfile
  template:
    src: Dockerfile.yaml.j2 #
    dest: /tmp/scraper/Dockerfile
    mode: 0700

- name: Копировать scraper
  copy:
    src: scraper #
    dest: /tmp/scraper/scraper
    mode: 0700

- name: Остановить Docker-контейнер (если существует)
  shell:
    cmd: docker stop scraper && docker rm scraper
  ignore_errors: yes

- name: Удалить старый Docker-образ (если существует)
  shell:
    cmd: docker rmi scraper_image
  ignore_errors: yes

# - name: Собрать Docker-образ
#   shell:
#     cmd: docker build -t scraper_image /tmp/scraper
#   args:
#     chdir: /tmp/scraper

# - name: Run Docker container
#   docker_container:
#     name: scraper
#     image: scraper_image
#     detach: yes
#     network_mode: host
#     networks_cli_compatible: yes
#     state: started