- name: =========================== Создаем папку в /tmp/ ===========================
  file:
    path: /tmp/influxdb
    state: directory

- name: =========================== Копируем скрипт №1 ===========================
  copy:
    src: entrypoint.sh 
    dest: /tmp/influxdb/entrypoint.sh
    mode: 0700

- name: =========================== Копируем скрипт №2 ===========================
  template:
    src: init-influxdb.sh.j2 
    dest: /tmp/influxdb/init-influxdb.sh.j2
    mode: 0700

- name: =========================== Копируем Dockerfile ===========================
  copy:
    src: Dockerfile #
    dest: /tmp/influxdb/Dockerfile
    mode: 0700

- name: =========================== Копируем influxdb.conf ===========================
  copy:
    src: influxdb.conf #
    dest: /tmp/influxdb/influxdb.conf
    mode: 0700

- name: =========================== Остановить Docker-контейнер (если существует) ===========================
  shell:
    cmd: docker stop influxdb && docker rm influxdb
  ignore_errors: yes
  register: docker_container_result

- name: =========================== Удалить старый Docker-образ (если существует) ===========================
  shell:
    cmd: docker rmi influxdb_image
  ignore_errors: yes
  register: docker_image_result

- name: =========================== Удалять нечего ===========================
  debug:
    msg: "Не пугайтесь ошибок выше.
      Если вы видите это сообщение, то скорее всего docker не удалил образ и/или контейнер, 
      что не является в данном playbook ошибкой. Только если в самой ошибке не указано иначе."

  when:
      - docker_container_result.failed
      - docker_image_result.failed
