- name: Создать папку
  file:
    path: /tmp/influxdb
    state: directory

- name: Копировать ###
  copy:
    src: entrypoint.sh #
    dest: /tmp/influxdb/entrypoint.sh
    mode: 0700

- name: Копировать ###
  template:
    src: init-influxdb.sh.j2 #
    dest: /tmp/influxdb/init-influxdb.sh.j2
    mode: 0700

- name: Копировать Dockerfile ########
  copy:
    src: Dockerfile #
    dest: /tmp/influxdb/Dockerfile
    mode: 0700

- name: Копировать influxdb.conf ########
  copy:
    src: influxdb.conf #
    dest: /tmp/influxdb/influxdb.conf
    mode: 0700

- name: Остановить Docker-контейнер (если существует)
  shell:
    cmd: docker stop influxdb && docker rm influxdb
  ignore_errors: yes

- name: Удалить старый Docker-образ (если существует)
  shell:
    cmd: docker rmi influxdb_image
  ignore_errors: yes

# - name: Собрать Docker-образ
#   shell:
#     cmd: docker build -t influxdb_image /tmp/influxdb


# - name: Run Docker container
#   docker_container:
#     name: influxdb
#     image: influxdb_image
#     state: started
#     network_mode: host

