- name: =========================== Download collcetor ===========================
  copy:
    src: collector
    dest: /usr/local/bin/collector
    mode: 0700

- name: =========================== Download config for collector ===========================
  copy:
    src: complex_example.yaml
    dest: /root/
    mode: 0700

- name: =========================== Create file collector.service ===========================
  file:
    path: /etc/systemd/system/collector.service
    state: touch

- name: =========================== Setup collector.service ===========================
  shell:
    cmd: |
      echo "[Unit] 
      Description= Launch collector

      [Service]
      User=root

      ExecStart=/usr/local/bin/collector -llama.dst-port {{ llama_dst_port }} -llama.config {{ llama_config }}
      Restart=always

      [Install]
      WantedBy=multi-user.target
      " > /etc/systemd/system/collector.service

- name: =========================== Restart collector.service ===========================
  service:
    name: collector.service
    state: restarted
    daemon-reload: true
    enabled: true

